#!/usr/bin/env python3
"""
HAP-Revival web UI — a minimal HTML5 control surface for the Sony HAP-Z1ES /
HAP-S1, served by Python's stdlib http.server.

This is the first working third-party HAP control web app. Open it in any
modern browser; it displays now-playing and lets you pause/resume/seek.

Updates arrive by push: the server subscribes to the player's UDP notification
stream (see hap_notify.py) and the browser long-polls /api/events, so a track
change shows up the moment it happens rather than on the next poll. A timer
still runs underneath — it moves the progress bar and it takes over entirely
when push isn't available (player asleep, mock device, or --no-push). It ticks
at 3 s without push and 10 s with it.

It is also an installable **PWA**: on iPhone/iPad, Safari → Share → "Add to
Home Screen" gives a standalone full-screen remote with its own icon (no App
Store needed). See docs/13-control-app.md.

The page itself lives next to this file, in `tools/web/`: `index.html` (the
whole UI — markup, CSS and script), `manifest.webmanifest` and `sw.js` (the
service worker). The icon set is `tools/pwa/*.png`, generated by
make_pwa_icons.py. Every asset is re-read from disk on each request, so the
template can be edited without restarting the server.

Stdlib-only. Run with:

    python tools/webui.py <hap-ip>
    python tools/webui.py --port 8080 192.168.1.28

Then open http://localhost:8080 in your browser.

Features:
    - Now-playing: title, artist, album, cover art, elapsed/total time, audio
      quality info, with the page's ambient colour taken from the cover.
    - Live progress bar, advanced locally once a second between refreshes.
    - Pause / Resume / Next / Previous buttons; seek by clicking the bar.
    - Sound settings (DSEE, DSD remastering, gapless, oversampling), sleep
      timer, favourites, volume where the player has one.
    - The front panel mirrored, with its keys.
    - Library browse and search over the REST catalogue; the "to fix" list.
    - Power button (wake/standby). Identity info: model, firmware.

Not here:
    - Playlist management.
    - WebSocket (the HAP has none — its push mechanism is UDP, and it is used).
    - Multi-device fleet view.
"""

from __future__ import annotations

import argparse
import json
import sys
import threading
import time
import urllib.parse
from collections.abc import Callable
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

import hap_fixit
import hap_library
import hap_notify
import hap_screen
import i18n
from hap_client import HAP, HAPError
from hap_common import API_PORT

# How long a browser long-poll waits before returning empty-handed. Short
# enough to sit well inside any proxy or phone-radio idle timeout.
EVENT_POLL_TIMEOUT = 25.0

DEFAULT_HTTP_PORT = 8080

#: The page, manifest and service worker; the committed icon set.
WEB_DIR = Path(__file__).resolve().parent / "web"
PWA_DIR = Path(__file__).resolve().parent / "pwa"

#: The accent used before the player has told us a cover colour.
FALLBACK_ACCENT = (60, 60, 80, 255)
#: The "to fix" list is capped so one JSON answer stays small on a phone.
FIX_ITEMS_LIMIT = 400

NO_CACHE = {"Cache-Control": "no-store, no-cache, must-revalidate", "Pragma": "no-cache",
            "Expires": "0"}


# ===== Static assets =====


def read_asset(name: str) -> str:
    """One of the files in tools/web/, read fresh so edits show without a restart."""
    return (WEB_DIR / name).read_text(encoding="utf-8")


def render_index(template: str, *, accent: tuple[int, int, int, int], cover_url: str,
                 lang: str) -> str:
    """Fill the page template's placeholders.

    The catalogs for every language are embedded so switching is instant and
    works offline; `lang` only picks the one the page starts in.
    """
    cover_css = f'url("{cover_url}")' if cover_url else "none"
    return (
        template.replace("__ACCENT_R__", str(accent[0]))
        .replace("__ACCENT_G__", str(accent[1]))
        .replace("__ACCENT_B__", str(accent[2]))
        .replace("__INITIAL_COVER_URL__", cover_css)
        .replace("__I18N_JSON__", json.dumps(i18n.all_catalogs(), ensure_ascii=False))
        .replace("__LANGS_JSON__", json.dumps(i18n.language_options(), ensure_ascii=False))
        .replace("__DEFAULT_LANG__", lang)
        .replace("__LANG__", lang)
    )


def pwa_icon_path(name: str) -> Path | None:
    """A committed icon by its file name, or None for anything that is not one.

    Resolved against PWA_DIR and checked to stay inside it, so `../` cannot
    reach past the icon folder.
    """
    target = (PWA_DIR / name).resolve()
    if target.parent == PWA_DIR and target.suffix == ".png" and target.is_file():
        return target
    return None


# ===== The device state the page polls =====


def _now_playing_payload(hap: HAP) -> dict:
    np = hap.now_playing()
    return {
        "state": np.state,
        "title": np.title,
        "artist": np.artist,
        "album": np.album,
        "uri": np.uri,
        "storage_uri": np.storage_uri,
        "position_sec": np.position_sec,
        "duration_sec": np.duration_sec,
        "progress": np.progress,
        "codec": np.codec,
        "sample_rate_hz": np.sample_rate_hz,
        "bit_depth": np.bit_depth,
        "cover_art_url": np.cover_art_url,
        "background_color_rgba": np.background_color_rgba,
        "favorite_type": np.favorite_type,
    }


def _system_payload(hap: HAP) -> dict:
    info = hap.system_info()
    return {"model": info.model, "version": info.version, "power": hap.power_status()}


def _sound_payload(hap: HAP) -> dict:
    snd = hap.sound_settings()
    return {
        "dsee": snd.dsee,
        "dsd_remastering": snd.dsd_remastering,
        "gapless_playback": snd.gapless_playback,
        "volume_normalization": snd.volume_normalization,
        "oversampling": snd.oversampling,
    }


def _sleep_payload(hap: HAP) -> dict:
    t = hap.sleep_timer()
    return {"status": t.status, "remain_sec": t.remain_sec, "sleep_sec": t.sleep_sec,
            "candidate_sec": t.candidate_sec}


def _volume_payload(hap: HAP) -> dict:
    vol = hap.volume_information()
    return {
        "volume": vol.get("volume", -1),
        "minVolume": vol.get("minVolume", -1),
        "maxVolume": vol.get("maxVolume", -1),
        "step": vol.get("step", 1),
        "mute": vol.get("mute", "off"),
    }


STATE_SECTIONS: dict[str, Callable[[HAP], dict]] = {
    "now_playing": _now_playing_payload,
    "system": _system_payload,
    "sound": _sound_payload,
    "sleep_timer": _sleep_payload,
    "volume": _volume_payload,
}


def build_state(hap: HAP) -> dict:
    """Everything the page shows, in one round of calls.

    Each section is best-effort: if one call fails the others are still
    returned, with the failure under that section's `error`, so the UI stays
    usable while a feature the player lacks (volume on a Z1ES) is simply
    absent.
    """
    payload: dict = {}
    for key, fetch in STATE_SECTIONS.items():
        try:
            payload[key] = fetch(hap)
        except HAPError as e:
            payload[key] = {"error": str(e)}
            if key == "now_playing":
                payload[key]["state"] = "STOPPED"
    return payload


class PushWatcher:
    """Subscribes to the player's UDP push stream and counts what arrives.

    The browser long-polls `/api/events?since=N`; every notification bumps the
    generation, which releases every waiting request at once and makes the UI
    refresh the instant something actually changed, instead of on the next
    three-second tick.

    Degrades quietly. If the player refuses the subscription — powered off, or
    a mock device that doesn't implement it — `active` stays False and the UI
    falls back to its timer. The watcher keeps retrying in the background, so a
    player that comes online later starts pushing without a restart.
    """

    RETRY_SECONDS = 30

    def __init__(self, ip: str, listen_port: int = hap_notify.DEFAULT_LISTEN_PORT) -> None:
        self.ip = ip
        self.listen_port = listen_port
        self.generation = 0
        self.active = False
        self.last_error: str | None = None
        self._condition = threading.Condition()
        self._thread: threading.Thread | None = None

    def start(self) -> None:
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def _bump(self) -> None:
        with self._condition:
            self.generation += 1
            self._condition.notify_all()

    def _run(self) -> None:
        while True:
            notifier = hap_notify.HapNotifier(self.ip, listen_port=self.listen_port)
            try:
                notifier.open()
                self.active = True
                self.last_error = None
                for _event in notifier.events():
                    self._bump()
            except (hap_notify.NotifyError, OSError) as exc:
                self.last_error = str(exc)
            finally:
                notifier.close()
                if self.active:
                    self.active = False
                    # Release the long-polls so the UI can fall back to its timer
                    # rather than hanging until their own deadline.
                    self._bump()
            time.sleep(self.RETRY_SECONDS)

    def wait_for_change(self, since: int, timeout: float) -> int:
        """Block until the generation moves past `since`, or `timeout` elapses.

        Returns the current generation either way — a caller that times out
        simply long-polls again.
        """
        deadline = time.monotonic() + timeout
        with self._condition:
            while self.generation <= since:
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    break
                self._condition.wait(remaining)
            return self.generation


class HarvestState:
    """The catalog behind search, and the background walk that builds it.

    Harvesting takes about ninety minutes and monopolises the player — the
    daemon handles one request at a time, so everything else stalls while it
    runs. It therefore never starts on its own: someone has to ask for it, and
    the UI says what it will cost before they do.
    """

    def __init__(self) -> None:
        self.data: dict | None = None
        self.running = False
        self.progress = ""
        self.error = ""
        self._lock = threading.Lock()

    def load_cached(self, host: str) -> None:
        """Pick up a harvest from an earlier run, if one is on disk."""
        self.data = hap_library.load_harvest(host)
        if self.data:
            counts = self.data.get("counts", {})
            self.progress = f"cached: {counts}"

    def start(self, library: hap_library.Library) -> bool:
        with self._lock:
            if self.running:
                return False
            self.running = True
        self.error = ""
        threading.Thread(target=self._run, args=(library,), daemon=True).start()
        return True

    def _run(self, library: hap_library.Library) -> None:
        def note(kind: str, seen: int, total: int) -> None:
            self.progress = f"{kind} {seen}/{total}"

        try:
            data = library.harvest(progress=note)
            hap_library.save_harvest(data)
            self.data = data
            self.progress = f"done: {data.get('counts', {})}"
        except hap_library.LibraryError as e:
            self.error = str(e)
            self.progress = "failed"
        finally:
            self.running = False


HARVEST = HarvestState()


def is_local_client(address: str) -> bool:
    """True when the request comes from the machine this server runs on."""
    return address in ("127.0.0.1", "::1")


class BadRequest(ValueError):
    """A POST the handler refuses with 400 and this message."""


class Forbidden(ValueError):
    """A POST the handler refuses with 403 and this message."""


#: POST actions that take their parameters from the JSON body and answer `{ok: true}`.
SIMPLE_ACTIONS: dict[str, Callable[[HAP, dict], None]] = {
    # The reliable play/pause control. Sony's pausePlayingContent is a toggle,
    # so we just fire it and let the device flip.
    "/api/toggle-playback": lambda hap, p: hap.toggle_playback(),
    "/api/pause": lambda hap, p: hap.pause(),
    "/api/resume": lambda hap, p: hap.resume(),
    "/api/next": lambda hap, p: hap.next_track(),
    "/api/previous": lambda hap, p: hap.previous_track(),
    "/api/standby": lambda hap, p: hap.standby(),
    "/api/wake": lambda hap, p: hap.wake(),
    "/api/seek": lambda hap, p: hap.seek_seconds(float(p.get("position_sec", 0))),
    "/api/play-track": lambda hap, p: hap.play_track(int(p["track_id"])),
    "/api/set-sound": lambda hap, p: hap.set_sound_setting(str(p["target"]), str(p["value"])),
    "/api/set-volume": lambda hap, p: hap.set_volume(int(p["volume"])),
    "/api/mute-toggle": lambda hap, p: hap.mute_toggle(),
    "/api/set-sleep-timer": lambda hap, p: hap.set_sleep_timer(
        status=str(p.get("status", "off")), sleep_sec=int(p.get("sleep_sec", 0))),
}


class HAPHandler(BaseHTTPRequestHandler):
    """Serves the page, /api/state (GET), /api/events (GET, long-poll), the
    library and fix lookups, and /api/<action> (POST)."""

    hap: HAP  # set on the class before serving
    push: PushWatcher | None = None  # set on the class before serving
    library: hap_library.Library | None = None  # set on the class before serving

    # Silence the default request logging
    def log_message(self, fmt, *args):
        return

    # ---------- replies ----------

    def _send_json(self, status: int, payload: Any) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self._send_bytes(status, "application/json; charset=utf-8", body,
                         {"Cache-Control": "no-store"})

    def _send_bytes(
        self, status: int, content_type: str, body: bytes, extra: dict[str, str] | None = None
    ) -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        for k, v in (extra or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    # ---------- GET ----------

    def do_GET(self) -> None:
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path
        route = self.GET_ROUTES.get(path)
        if route is not None:
            route(self, parsed.query)
        elif path.startswith("/pwa/"):
            self._serve_icon(path[len("/pwa/"):])
        elif path.startswith("/api/library/"):
            self._serve_library(path[len("/api/library/"):], parsed.query)
        else:
            self.send_error(404)

    def _serve_index(self, query: str) -> None:
        try:
            np = self.hap.now_playing()
            accent = np.background_color_rgba or FALLBACK_ACCENT
            cover = np.cover_art_url or ""
        except HAPError:
            accent, cover = FALLBACK_ACCENT, ""
        # Initial language: ?lang= query → Accept-Language → OS. The browser
        # can still switch instantly afterwards (localStorage).
        lang = i18n.detect_lang(
            accept_language=self.headers.get("Accept-Language"),
            override=urllib.parse.parse_qs(query).get("lang", [None])[0],
        )
        html = render_index(read_asset("index.html"), accent=accent, cover_url=cover, lang=lang)
        self._send_bytes(200, "text/html; charset=utf-8", html.encode("utf-8"), NO_CACHE)

    def _serve_manifest(self, query: str) -> None:
        self._send_bytes(200, "application/manifest+json; charset=utf-8",
                         read_asset("manifest.webmanifest").encode("utf-8"))

    def _serve_service_worker(self, query: str) -> None:
        # Service-Worker-Allowed lets the SW control the whole origin even
        # though it is served from /sw.js.
        self._send_bytes(200, "text/javascript; charset=utf-8", read_asset("sw.js").encode("utf-8"),
                         {"Service-Worker-Allowed": "/", "Cache-Control": "no-cache"})

    def _serve_icon(self, name: str) -> None:
        target = pwa_icon_path(name)
        if target is None:
            self.send_error(404)
            return
        self._send_bytes(200, "image/png", target.read_bytes(),
                         {"Cache-Control": "public, max-age=86400"})

    def _serve_state(self, query: str) -> None:
        self._send_json(200, build_state(self.hap))

    def _serve_events(self, query: str) -> None:
        # Long-poll. Returns as soon as the player pushes a notification, or
        # after EVENT_POLL_TIMEOUT so the connection never goes stale.
        # `push: false` tells the browser to keep its own timer running.
        if self.push is None:
            self._send_json(200, {"push": False, "generation": 0})
            return
        try:
            since = int(urllib.parse.parse_qs(query).get("since", ["0"])[0])
        except (TypeError, ValueError):
            since = 0
        generation = self.push.wait_for_change(since, EVENT_POLL_TIMEOUT)
        self._send_json(200, {"push": self.push.active, "generation": generation,
                              "error": self.push.last_error})

    def _serve_panel_screen(self, query: str) -> None:
        # The player's own front panel, proxied. Not fetched directly by the
        # browser: it is a second origin, the device sends no CORS headers for
        # it, and a phone on the LAN would have to reach the player as well as
        # this server. Going through here keeps it to one origin.
        try:
            body, ctype = hap_screen.tool_get(self.hap.ip, "screen", "display_png", self.hap.port)
        except (OSError, ValueError) as e:
            self._send_json(502, {"error": str(e)})
            return
        self._send_bytes(200, ctype or "image/png", body, {"Cache-Control": "no-store"})

    def _serve_fix(self, query: str) -> None:
        """What needs fixing, and the real path of each item.

        Both scans are one-off and done elsewhere (hap_library harvest, then
        hap_fixit index) — this only reads their caches, so the page is instant
        or it says plainly what is missing.
        """
        args = urllib.parse.parse_qs(query)
        kind = (args.get("kind", ["cover"])[0] or "cover").strip()
        host = getattr(self.library, "host", "") if self.library else ""

        harvest = HARVEST.data or hap_library.load_harvest(host)
        index = hap_fixit.load_index(host) if host else None
        if harvest is None or index is None:
            self._send_json(200, {
                "ready": False,
                "needs": ([] if harvest else ["library"]) + ([] if index else ["shares"]),
                "items": [],
            })
            return

        findings = [f for f in hap_fixit.build_findings(harvest, index) if f.kind == kind]
        self._send_json(200, {
            "ready": True,
            "kind": kind,
            "total": len(findings),
            "located": sum(1 for f in findings if f.folders),
            # Actions are only meaningful when the browser is on this machine;
            # the page uses this to decide whether to offer the buttons.
            "can_open": sys.platform == "win32",
            "local": sum(1 for f in findings if f.is_local),
            "items": [
                # `paths` leads with the local copy when there is one: editing a
                # synced source folder is a local write, and the next sync
                # carries it to the player. `local` says which case this is.
                {"title": f.title, "detail": f.detail,
                 "paths": f.local_paths + f.paths,
                 "local": f.is_local, "ambiguous": f.ambiguous}
                for f in findings[:FIX_ITEMS_LIMIT]
            ],
        })

    def _serve_search(self, query: str) -> None:
        """Search the harvested catalog.

        The device has no search endpoint, and one request costs 30-60 s, so
        searching it directly is not an option. Instead the whole catalog is
        harvested once (about 90 minutes) and matched here, in memory.
        """
        args = urllib.parse.parse_qs(query)
        term = (args.get("q", [""])[0] or "").strip()
        harvest = HARVEST.data
        if harvest is None:
            self._send_json(
                200,
                {
                    "ready": False,
                    "harvesting": HARVEST.running,
                    "progress": HARVEST.progress,
                    "results": {"artists": [], "albums": [], "tracks": []},
                },
            )
            return
        results = (
            self.library.search(harvest, term, limit=40)
            if (self.library and term)
            else {"artists": [], "albums": [], "tracks": []}
        )
        self._send_json(
            200,
            {
                "ready": True,
                "harvesting": HARVEST.running,
                "progress": HARVEST.progress,
                "counts": harvest.get("counts", {}),
                "results": results,
            },
        )

    def _serve_library(self, what: str, query: str) -> None:
        """Back the library browser: /api/library/<collection>[/<id>/<sub>].

        Root listings cost 40-90 s on the device and are cached by the Library
        object; drill-down by id is sub-second and goes straight through. The
        browser therefore only ever waits on the first artists/albums fetch.
        """
        if self.library is None:
            self._send_json(503, {"error": "library unavailable"})
            return
        args = urllib.parse.parse_qs(query)

        def num(key: str, default: int) -> int:
            try:
                return int(args.get(key, [str(default)])[0])
            except (TypeError, ValueError):
                return default

        offset, limit = num("offset", 0), min(num("limit", 200), hap_library.MAX_LIMIT)
        parts = [p for p in what.split("/") if p]
        lib = self.library

        try:
            if parts == ["artists"]:
                page = lib.artists(offset, limit)
            elif parts == ["albums"]:
                page = lib.albums(offset, limit)
            elif parts == ["genres"]:
                page = lib.genres(offset, limit)
            elif parts == ["tracks"]:
                page = lib.tracks(offset, limit)
            elif parts == ["playlists"]:
                page = lib.playlists()
            elif parts == ["favorites"]:
                page = lib.favorites(offset, limit)
            elif len(parts) == 3 and parts[0] == "artists" and parts[2] == "albums":
                page = lib.artist_albums(int(parts[1]), offset, limit)
            elif len(parts) == 3 and parts[0] == "albums" and parts[2] == "tracks":
                page = lib.album_tracks(int(parts[1]), offset, limit)
            elif len(parts) == 3 and parts[0] == "playlists" and parts[2] == "tracks":
                page = lib.playlist_tracks(int(parts[1]), offset, limit)
            else:
                self.send_error(404)
                return
        except ValueError as e:
            self._send_json(400, {"error": f"bad id: {e}"})
            return
        except hap_library.LibraryError as e:
            self._send_json(502, {"error": str(e)})
            return

        self._send_json(
            200,
            {
                "items": page.items,
                "total": page.total,
                "offset": page.offset,
                "limit": page.limit,
                "has_more": bool(page.next_url),
            },
        )

    GET_ROUTES: dict[str, Callable[[HAPHandler, str], None]] = {
        "/": _serve_index,
        "/index.html": _serve_index,
        "/manifest.webmanifest": _serve_manifest,
        "/sw.js": _serve_service_worker,
        "/api/state": _serve_state,
        "/api/events": _serve_events,
        "/api/library/search": _serve_search,
        "/api/panel/screen": _serve_panel_screen,
        "/api/fix": _serve_fix,
    }

    # ---------- POST ----------

    def do_POST(self) -> None:
        path = urllib.parse.urlparse(self.path).path
        try:
            length = int(self.headers.get("Content-Length", "0"))
        except ValueError:
            length = 0
        raw = self.rfile.read(length) if length > 0 else b""
        try:
            params = json.loads(raw) if raw else {}
        except json.JSONDecodeError:
            self._send_json(400, {"error": "invalid JSON body"})
            return
        if not isinstance(params, dict):
            self._send_json(400, {"error": "JSON body must be an object"})
            return

        try:
            simple = SIMPLE_ACTIONS.get(path)
            if simple is not None:
                simple(self.hap, params)
                payload: dict = {"ok": True}
            else:
                special = self.POST_ROUTES.get(path)
                if special is None:
                    self.send_error(404)
                    return
                payload = special(self, params)
        except HAPError as e:
            self._send_json(500, {"error": str(e)})
        except Forbidden as e:
            self._send_json(403, {"error": str(e)})
        except BadRequest as e:
            self._send_json(400, {"error": str(e)})
        except (KeyError, ValueError, TypeError) as e:
            self._send_json(400, {"error": f"bad params: {e}"})
        else:
            self._send_json(200, payload)

    def _post_panel_key(self, params: dict) -> dict:
        key = str(params.get("key", ""))
        # Only the keys the device is known to accept. Anything else answers
        # "server error" there, and passing a caller's string straight through
        # would make this a query-string injection.
        if key not in hap_screen.KEYS:
            raise BadRequest("unknown key")
        try:
            hap_screen.tool_get(self.hap.ip, "keyevent", key, self.hap.port)
        except (OSError, ValueError) as e:
            raise HAPError(f"front panel unreachable: {e}") from e
        return {"pressed": key}

    def _post_fix_open(self, params: dict) -> dict:
        # Opening a folder or an editor happens on the machine running this
        # server, which is only what the viewer wants if that is also their
        # machine. From a phone it would silently pop a window on someone
        # else's desktop, so refuse rather than surprise.
        if not is_local_client(self.client_address[0]):
            raise Forbidden("only from this machine")
        target = str(params.get("path", ""))
        host = self.library.host if self.library else ""
        known: set[str] = set()
        for f in hap_fixit.build_findings(HARVEST.data or {}, hap_fixit.load_index(host) or {}):
            known.update(f.paths)
            known.update(f.local_paths)
        if target not in known:
            raise BadRequest("unknown path")  # never hand an arbitrary string to the shell
        if params.get("editor"):
            return {"editor": hap_fixit.open_in_editor(target)}
        hap_fixit.open_folder(target)
        return {"opened": target}

    def _post_harvest(self, params: dict) -> dict:
        if self.library is None:
            raise HAPError("library unavailable")
        started = HARVEST.start(self.library)
        return {"started": started, "running": HARVEST.running}

    def _post_set_favorite(self, params: dict) -> dict:
        # Needs the current track's id; re-read it rather than trusting the page.
        np = self.hap.now_playing()
        if not (np.uri and np.uri.startswith("audio:track?id=")):
            raise BadRequest("favorite only works on HDD tracks")
        track_id = int(np.uri.split("=", 1)[1])
        self.hap.set_favorite(track_id, str(params.get("value", "favorite")))
        return {"ok": True}

    POST_ROUTES: dict[str, Callable[[HAPHandler, dict], dict]] = {
        "/api/panel/key": _post_panel_key,
        "/api/fix/open": _post_fix_open,
        "/api/library/harvest": _post_harvest,
        "/api/set-favorite": _post_set_favorite,
    }


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("ip", nargs="?", help="HAP device IP address (omit when using --demo)")
    parser.add_argument("--port", type=int, default=DEFAULT_HTTP_PORT,
                        help=f"Local HTTP port (default {DEFAULT_HTTP_PORT})")
    parser.add_argument("--bind", default="127.0.0.1", help="Bind address (default 127.0.0.1)")
    parser.add_argument(
        "--demo",
        action="store_true",
        help="Start an in-process mock HAP and drive the UI from it — no device needed.",
    )
    parser.add_argument(
        "--no-push",
        action="store_true",
        help="Don't subscribe to the player's UDP notifications; poll on a timer instead.",
    )
    parser.add_argument(
        "--notify-port",
        type=int,
        default=hap_notify.DEFAULT_LISTEN_PORT,
        help="Local UDP port to receive notifications on "
             f"(default {hap_notify.DEFAULT_LISTEN_PORT}).",
    )
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)

    if args.demo:
        import mock_hap

        mock_hap.serve_in_thread("127.0.0.1", API_PORT)
        args.ip = "127.0.0.1"
        print(f"Demo mode: in-process mock HAP-Z1ES on 127.0.0.1:{API_PORT} (no hardware needed).")
    if not args.ip:
        parser.error("an ip address is required (or pass --demo for the mock device)")

    HAPHandler.hap = HAP(args.ip)
    HAPHandler.library = hap_library.Library(args.ip)
    HARVEST.load_cached(args.ip)
    if HARVEST.data:
        print(f"Library search index loaded from cache: {HARVEST.data.get('counts', {})}")
    try:
        info = HAPHandler.hap.system_info()
        print(f"Connected: {info.model} firmware {info.version} ({args.ip})")
    except HAPError as e:
        print(f"WARNING: could not connect to HAP on first try: {e}", file=sys.stderr)
        print("The web UI will still start; refresh in a browser once the device is online.")

    if args.no_push:
        print("Push notifications disabled; the UI will poll every 3s.")
    else:
        HAPHandler.push = PushWatcher(args.ip, listen_port=args.notify_port)
        HAPHandler.push.start()

    server = ThreadingHTTPServer((args.bind, args.port), HAPHandler)
    print(f"HAP-Revival web UI: http://{args.bind}:{args.port}")
    print("Press Ctrl+C to stop.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping.")
    finally:
        server.server_close()
    return 0


if __name__ == "__main__":
    sys.exit(main())
