#!/usr/bin/env python3
"""
HAP-Revival web UI — a minimal HTML5 control surface for the Sony HAP-Z1ES /
HAP-S1, served by Python's stdlib http.server.

This is the first working third-party HAP control web app. Open it in any
modern browser; it displays now-playing and lets you pause/resume/seek.

Updates arrive by push: the server subscribes to the player's UDP notification
stream (see hap_notify.py) and the browser long-polls /api/events, so a track
change shows up the moment it happens rather than on the next poll. A timer
still runs underneath — it moves the progress bar and it takes over entirely
when push isn't available (player asleep, mock device, or --no-push). It ticks
at 3 s without push and 10 s with it.

It is also an installable **PWA**: on iPhone/iPad, Safari → Share → "Add to
Home Screen" gives a standalone full-screen remote with its own icon (no App
Store needed). See docs/13-control-app.md. The manifest (/manifest.webmanifest),
icon set (/pwa/*.png, generated by make_pwa_icons.py) and service worker
(/sw.js) are all served from this one file, stdlib-only.

Stdlib-only. Run with:

    python tools/webui.py <hap-ip>
    python tools/webui.py --port 8080 192.168.1.28

Then open http://localhost:8080 in your browser.

Features in this V0:
    - Now-playing: title, artist, album, cover art (with cross-CDN proxy for
      Spotify Connect album art), elapsed/total time, audio quality info.
    - Live progress bar, advanced locally once a second between refreshes.
    - Pause / Resume / Next / Previous buttons.
    - Seek by clicking on the progress bar.
    - Sound settings (DSEE, DSD remastering, gapless, oversampling) — read-only.
    - Power button (wake/standby).
    - Identity info: model, firmware, MAC.

Not in V0:
    - Library browse (waiting on downloadByDiff to return non-empty location).
    - Playlist management.
    - WebSocket (the HAP has none — its push mechanism is UDP, and it is used).
    - Multi-device fleet view.
"""

from __future__ import annotations

import argparse
import json
import sys
import threading
import time
import urllib.parse
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from pathlib import Path
from typing import Any

# Allow `python tools/webui.py …` from repo root
sys.path.insert(0, str(Path(__file__).resolve().parent))

import hap_library  # noqa: E402
import hap_notify  # noqa: E402
import i18n  # noqa: E402
from hap_client import HAP, HAPError  # noqa: E402

# How long a browser long-poll waits before returning empty-handed. Short
# enough to sit well inside any proxy or phone-radio idle timeout.
EVENT_POLL_TIMEOUT = 25.0


_TEMPLATE_OPEN = "# >>> HTML_PAGE TEMPLATE BEGIN >>>"
_TEMPLATE_CLOSE = "# <<< HTML_PAGE TEMPLATE END <<<"


def _live_html_template() -> str | None:
    """Re-read the HTML_PAGE constant out of our own source file on each
    request. Lets contributors iterate on the template/CSS without having
    to bounce the server.

    Looks for the explicit `_TEMPLATE_OPEN` / `_TEMPLATE_CLOSE` sentinel
    comments around the assignment — using the assignment text itself as a
    search anchor would falsely match the literal string written *here*
    (this very `find()` call). Returns None on any failure; the caller
    then falls back to the module-level constant.
    """
    try:
        src = Path(__file__).resolve().read_text(encoding="utf-8")
        # Find the LAST occurrence of the open sentinel so we never match
        # an in-source reference to it (e.g. this docstring).
        open_idx = src.rfind(_TEMPLATE_OPEN)
        close_idx = src.rfind(_TEMPLATE_CLOSE)
        if open_idx < 0 or close_idx < 0 or close_idx <= open_idx:
            return None
        block = src[open_idx:close_idx]
        # Now extract the """...""" body inside that block.
        q1 = block.find('"""')
        if q1 < 0:
            return None
        q2 = block.find('"""', q1 + 3)
        if q2 < 0:
            return None
        return block[q1 + 3 : q2]
    except OSError:
        return None


# >>> HTML_PAGE TEMPLATE BEGIN >>>
HTML_PAGE = """<!doctype html>
<html lang="__LANG__">
<head>
<meta charset="utf-8" />
<title data-i18n="web.title">HAP-Revival — control</title>
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover" />
<!-- PWA: installable on iPhone/iPad home screen via Safari → Share → "Add to Home Screen" -->
<link rel="manifest" href="/manifest.webmanifest" />
<meta name="theme-color" content="#0e0e10" />
<meta name="mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-capable" content="yes" />
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
<meta name="apple-mobile-web-app-title" content="HAP" />
<link rel="apple-touch-icon" href="/pwa/apple-touch-icon.png" />
<link rel="icon" type="image/png" sizes="192x192" href="/pwa/icon-192.png" />
<style>
* { box-sizing: border-box; margin: 0; padding: 0; }
:root {
  --bg: #0e0e10; --fg: #f0f0f0; --muted: #aaa;
  --accent: rgb(__ACCENT_R__, __ACCENT_G__, __ACCENT_B__);
  --accent-soft: rgba(__ACCENT_R__, __ACCENT_G__, __ACCENT_B__, 0.35);
  --card-bg: rgba(20,20,24,0.55); --hover: rgba(255,255,255,0.12);
  --cover-url: __INITIAL_COVER_URL__;
  --custom-bg: #1a1f2c;
  --text-shadow: 0 1px 3px rgba(0,0,0,0.5);
}
/* When the background is bright, swap to dark text + light glass cards so the
   UI stays legible. The `bg-is-light` class is set/cleared in JS based on the
   computed luminance of the dominant background color (cover accent / custom
   color / etc.). */
html.bg-is-light {
  --fg: #111;
  --muted: #444;
  --card-bg: rgba(255,255,255,0.45);
  --hover: rgba(0,0,0,0.08);
  --text-shadow: 0 1px 3px rgba(255,255,255,0.4);
}
html { background: var(--bg); color: var(--fg); font-family: -apple-system, BlinkMacSystemFont, "SF Pro Text", "Segoe UI", Helvetica, Arial, sans-serif; min-height: 100vh; overflow-x: hidden; }
/* body MUST stay transparent — otherwise it covers body::before (the ambient bg
   layer below sits at z-index:-2, which puts it behind body's own background). */
body { background: transparent; color: var(--fg); display: flex; flex-direction: column; align-items: center; padding: 24px 16px; position: relative; min-height: 100vh; }

/* Ambient cover background: heavily blurred cover, scaled up, behind everything.
   This is what gives the "diffuse colors from the album art" feeling.
   Tuning notes: blur too high or opacity too low + dark overlay = invisible.
   With muted covers, saturation boost matters most. */
body::before {
  content: "";
  position: fixed;
  inset: -15vh -15vw;
  background-image: var(--cover-url);
  background-size: cover;
  background-position: center;
  background-repeat: no-repeat;
  filter: blur(60px) saturate(1.8) brightness(1.05);
  opacity: 1.0;
  z-index: -2;
  transition: opacity 0.6s ease, background-color 0.4s ease;
  /* Fallback solid color if no cover yet */
  background-color: var(--accent);
}
/* Light vignette only — preserve as much color as possible while keeping
   text readable. Top kept transparent, bottom only slightly darker. */
body::after {
  content: "";
  position: fixed;
  inset: 0;
  background:
    radial-gradient(ellipse at center, rgba(14,14,16,0) 0%, rgba(14,14,16,0.1) 70%, rgba(14,14,16,0.35) 100%);
  z-index: -1;
  pointer-events: none;
  transition: background 0.4s ease;
}

/* ===== Theme overrides (data-theme on <html>) =====
   !important kept on every override so no specificity surprise can shadow them
   (the body::before rule above uses CSS variables which can otherwise win
   when set inline on documentElement). */

/* "cover-solid" — single solid color = the RGB the HAP extracts from the cover.
   Disables the blurred image, keeps the accent color as the flat background. */
html[data-theme="cover-solid"] body::before {
  background-image: none !important;
  background-color: var(--accent) !important;
  filter: none !important;
  opacity: 1 !important;
}
html[data-theme="cover-solid"] body::after { background: none !important; }

/* "dark" — pure dark, no ambient at all. */
html[data-theme="dark"] body::before {
  background-image: none !important;
  background-color: var(--bg) !important;
  filter: none !important;
  opacity: 1 !important;
}
html[data-theme="dark"] body::after { background: none !important; }

/* "custom" — single solid color picked by the user via the color picker. */
html[data-theme="custom"] body::before {
  background-image: none !important;
  background-color: var(--custom-bg) !important;
  filter: none !important;
  opacity: 1 !important;
}
html[data-theme="custom"] body::after { background: none !important; }

/* Minimal mode: hide the title bar (header) and the bottom footer so only
   the now-playing card + the gear are visible. The card alone is enough
   info; everything else is meta. */
html.minimal header,
html.minimal footer { display: none; }
header { text-align: center; margin-bottom: 24px; }
header h1 { font-size: 18px; font-weight: 500; letter-spacing: 0.04em; opacity: 0.85; text-shadow: var(--text-shadow); }
header .device { font-size: 12px; color: var(--muted); margin-top: 4px; text-shadow: var(--text-shadow); }
footer { text-shadow: var(--text-shadow); }
main { width: 100%; max-width: 520px; }
.card {
  background: var(--card-bg);
  border-radius: 16px;
  padding: 24px;
  margin-bottom: 16px;
  backdrop-filter: blur(28px) saturate(1.2);
  -webkit-backdrop-filter: blur(28px) saturate(1.2);
  border: 1px solid rgba(255,255,255,0.06);
  box-shadow: 0 8px 32px rgba(0,0,0,0.35);
  transition: background 0.4s ease;
}
#now-playing { display: flex; flex-direction: column; align-items: center; gap: 16px; min-height: 360px; }
.cover {
  width: 240px;
  height: 240px;
  border-radius: 12px;
  background: #222 no-repeat center/cover;
  box-shadow:
    0 10px 40px rgba(0,0,0,0.6),
    0 0 60px 0 var(--accent-soft);
  transition: background-image 0.6s ease, box-shadow 0.8s ease;
}
.cover.placeholder::before { content: "♪"; display: flex; align-items: center; justify-content: center; height: 100%; font-size: 80px; color: #444; }
.meta { text-align: center; }
.meta .title { font-size: 22px; font-weight: 600; margin-bottom: 6px; }
.meta .artist { font-size: 15px; opacity: 0.85; }
.meta .album { font-size: 13px; opacity: 0.6; margin-top: 4px; }
.meta .tech { font-size: 11px; color: var(--muted); margin-top: 8px; letter-spacing: 0.05em; }
.state-tag { display: inline-block; padding: 2px 10px; border-radius: 10px; font-size: 10px; letter-spacing: 0.1em; text-transform: uppercase; background: var(--accent); color: white; opacity: 0.8; margin-bottom: 8px; }
.state-tag.STOPPED { background: #555; }
.state-tag.PAUSED { background: #c80; }
.state-tag.PLAYING { background: var(--accent); }
.progress-wrap { width: 100%; }
.progress-bar { width: 100%; height: 6px; background: rgba(255,255,255,0.1); border-radius: 3px; cursor: pointer; overflow: hidden; }
.progress-fill { height: 100%; background: var(--accent); border-radius: 3px; transition: width 0.4s ease; }
.progress-times { display: flex; justify-content: space-between; font-size: 11px; color: var(--muted); margin-top: 6px; }
.controls { display: flex; justify-content: center; gap: 8px; }
.btn { background: var(--card-bg); color: var(--fg); border: 0; border-radius: 999px; padding: 12px 20px; font-size: 14px; cursor: pointer; transition: background 0.15s; min-width: 56px; }
.btn:hover, .btn:focus-visible { background: var(--hover); outline: 0; }
.btn.primary { background: var(--accent); color: white; font-weight: 600; padding: 14px 28px; }
.btn.danger:hover { background: #a00; }
.settings { font-size: 12px; }
.settings table { width: 100%; }
.settings td { padding: 4px 0; }
.settings td.k { color: var(--muted); text-transform: uppercase; letter-spacing: 0.08em; font-size: 10px; }
.settings td.v { text-align: right; font-weight: 500; }

/* ===== Library browser ===== */
.library { font-size: 13px; }
.lib-head { display: flex; align-items: center; justify-content: space-between; }
.lib-title { text-transform: uppercase; letter-spacing: 0.08em; font-size: 10px; color: var(--muted); }
.lib-toggle { background: var(--card-bg); color: var(--fg); border: 0; border-radius: 999px; padding: 6px 14px; font-size: 12px; cursor: pointer; }
.lib-toggle:hover { background: var(--hover); }
.lib-tabs { display: flex; flex-wrap: wrap; gap: 6px; margin: 12px 0 8px; }
.lib-tab { background: var(--card-bg); color: var(--fg); border: 0; border-radius: 999px; padding: 6px 12px; font-size: 12px; cursor: pointer; }
.lib-tab:hover, .lib-tab.on { background: var(--accent); color: #fff; }
.lib-search { width: 100%; box-sizing: border-box; background: var(--card-bg); color: var(--fg); border: 0; border-radius: 999px; padding: 8px 14px; font-size: 13px; margin-bottom: 8px; }
.lib-search:focus { outline: 2px solid var(--accent-soft); }
.lib-crumbs { font-size: 11px; color: var(--muted); margin-bottom: 6px; min-height: 14px; }
.lib-crumbs button { background: none; border: 0; color: var(--muted); text-decoration: underline; cursor: pointer; font-size: 11px; padding: 0; }
/* Capped so a 78 000-track library cannot make the page scroll forever. */
.lib-list { max-height: 46vh; overflow-y: auto; -webkit-overflow-scrolling: touch; }
.lib-row { display: flex; align-items: baseline; gap: 8px; padding: 8px 4px; border-bottom: 1px solid var(--hover); cursor: pointer; }
.lib-row:hover { background: var(--hover); }
.lib-row .n { flex: 1; overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }
.lib-row .s { color: var(--muted); font-size: 11px; white-space: nowrap; }
.lib-row.playing .n { color: var(--accent); font-weight: 600; }
.lib-foot { display: flex; flex-direction: column; gap: 6px; margin-top: 10px; }
.lib-more { background: var(--card-bg); color: var(--fg); border: 0; border-radius: 999px; padding: 8px 16px; font-size: 12px; cursor: pointer; align-self: flex-start; }
.lib-more:hover { background: var(--hover); }
.lib-msg { color: var(--muted); padding: 10px 4px; font-size: 12px; }
footer { color: var(--muted); font-size: 11px; margin-top: 32px; text-align: center; }
footer a { color: var(--muted); text-decoration: underline; }
.error { background: #422; color: #f88; padding: 12px; border-radius: 8px; font-size: 13px; }

/* ===== Settings panel ===== */
.gear-wrap { position: fixed; top: 16px; right: 16px; z-index: 100; }
.gear-btn {
  background: var(--card-bg);
  color: var(--fg);
  border: 0;
  border-radius: 999px;
  width: 36px; height: 36px;
  font-size: 18px;
  cursor: pointer;
  backdrop-filter: blur(20px);
  -webkit-backdrop-filter: blur(20px);
  transition: background 0.15s, transform 0.3s;
  display: flex; align-items: center; justify-content: center;
}
.gear-btn:hover { background: var(--hover); }
.gear-btn.open { transform: rotate(60deg); }
.settings-panel {
  position: absolute;
  top: 44px; right: 0;
  width: 300px;
  max-height: 85vh;
  overflow-y: auto;
  background: rgba(20,20,24,0.92);
  border: 1px solid rgba(255,255,255,0.08);
  border-radius: 12px;
  padding: 12px;
  backdrop-filter: blur(28px) saturate(1.2);
  -webkit-backdrop-filter: blur(28px) saturate(1.2);
  box-shadow: 0 12px 40px rgba(0,0,0,0.5);
  display: none;
  font-size: 13px;
}
.settings-panel + .settings-panel-section,
.settings-panel section + section {
  margin-top: 16px;
  padding-top: 12px;
  border-top: 1px solid rgba(255,255,255,0.06);
}
.settings-panel.open { display: block; }
.settings-panel h3 {
  font-size: 10px;
  font-weight: 600;
  letter-spacing: 0.12em;
  text-transform: uppercase;
  color: var(--muted);
  margin-bottom: 8px;
}
.theme-option {
  display: flex; align-items: center;
  padding: 8px 10px;
  border-radius: 8px;
  cursor: pointer;
  transition: background 0.12s;
  gap: 10px;
  border: 1px solid transparent;
}
.theme-option:hover { background: var(--hover); }
.theme-option.active {
  background: var(--accent-soft);
  border-color: var(--accent);
}
.theme-option input[type=radio] { accent-color: var(--accent); cursor: pointer; }
.theme-option label { cursor: pointer; flex: 1; }
.theme-debug {
  margin-top: 10px;
  padding-top: 8px;
  border-top: 1px solid rgba(255,255,255,0.08);
  font-size: 10px;
  color: var(--muted);
  text-align: center;
}
.theme-option input[type=color] {
  width: 28px; height: 28px;
  border: 0; padding: 0;
  background: transparent;
  border-radius: 6px;
  cursor: pointer;
}

/* === Settings rows (sound / playback / favorite) === */
.set-row {
  display: flex; align-items: center; justify-content: space-between;
  padding: 6px 0; gap: 12px; font-size: 12px;
}
.set-row .k { color: var(--muted); text-transform: uppercase; letter-spacing: 0.06em; font-size: 10px; flex: 1; }
.set-row select, .set-row input[type=range] {
  color: var(--fg); background: rgba(0,0,0,0.25);
  border: 1px solid rgba(255,255,255,0.08); border-radius: 6px;
  padding: 3px 6px; font-size: 12px;
}
.set-row select { min-width: 110px; }
.set-row input[type=range] { width: 130px; accent-color: var(--accent); }
html.bg-is-light .set-row select, html.bg-is-light .set-row input[type=range] {
  background: rgba(255,255,255,0.6); border-color: rgba(0,0,0,0.1);
}
/* Two-state pill toggle */
.pill-toggle {
  display: inline-flex; background: rgba(0,0,0,0.25); border-radius: 999px;
  padding: 2px; border: 1px solid rgba(255,255,255,0.08);
}
.pill-toggle button {
  background: transparent; color: var(--muted); border: 0;
  padding: 4px 10px; font-size: 11px; border-radius: 999px;
  cursor: pointer; transition: background 0.15s, color 0.15s;
}
.pill-toggle button.active { background: var(--accent); color: white; font-weight: 600; }
html.bg-is-light .pill-toggle { background: rgba(255,255,255,0.6); border-color: rgba(0,0,0,0.1); }
/* Three-button row for favorite */
.fav-row { display: flex; gap: 6px; }
.fav-row button {
  flex: 1; background: rgba(0,0,0,0.25); color: var(--fg);
  border: 1px solid rgba(255,255,255,0.08);
  padding: 6px 0; font-size: 14px; border-radius: 8px; cursor: pointer;
  transition: background 0.15s, color 0.15s;
}
.fav-row button:disabled { opacity: 0.35; cursor: not-allowed; }
.fav-row button.active { background: var(--accent); color: white; }
html.bg-is-light .fav-row button { background: rgba(255,255,255,0.5); border-color: rgba(0,0,0,0.1); }
.set-note { font-size: 10px; color: var(--muted); margin-top: 4px; line-height: 1.4; }
/* Section dividers inside the settings panel */
.settings-panel section { margin-top: 16px; padding-top: 12px; border-top: 1px solid rgba(255,255,255,0.06); }
.settings-panel section h3 {
  font-size: 10px; font-weight: 600; letter-spacing: 0.12em;
  text-transform: uppercase; color: var(--muted); margin-bottom: 8px;
}
</style>
</head>
<body>
<div class="gear-wrap">
  <button class="gear-btn" id="gear-btn" onclick="toggleSettings()" title="Settings" aria-label="Settings">⚙</button>
  <div class="settings-panel" id="settings-panel">
    <h3 data-i18n="web.lang.title">Language</h3>
    <div class="set-row">
      <select id="lang-sel" onchange="setLang(this.value)" style="min-width:100%"></select>
    </div>

    <section>
    <h3 data-i18n="web.bg.title">Background</h3>
    <div class="theme-option" id="opt-ambient">
      <input type="radio" name="theme" id="t-ambient" value="ambient" onchange="setTheme('ambient')">
      <label for="t-ambient" data-i18n="web.bg.ambient">Ambient cover</label>
    </div>
    <div class="theme-option" id="opt-cover-solid">
      <input type="radio" name="theme" id="t-cover-solid" value="cover-solid" onchange="setTheme('cover-solid')">
      <label for="t-cover-solid" data-i18n="web.bg.cover_solid">Solid (from cover)</label>
    </div>
    <div class="theme-option" id="opt-dark">
      <input type="radio" name="theme" id="t-dark" value="dark" onchange="setTheme('dark')">
      <label for="t-dark" data-i18n="web.bg.dark">Dark</label>
    </div>
    <div class="theme-option" id="opt-custom">
      <input type="radio" name="theme" id="t-custom" value="custom" onchange="setTheme('custom')">
      <label for="t-custom" data-i18n="web.bg.custom">Custom</label>
      <input type="color" id="custom-color" value="#1a1f2c" oninput="setCustomColor(this.value)">
    </div>
    <div class="theme-debug" id="theme-debug">current: ambient</div>
    </section>

    <section>
      <h3 data-i18n="web.display.title">Display</h3>
      <div class="set-row">
        <span class="k" data-i18n="web.display.minimal">Minimal mode</span>
        <span class="pill-toggle" id="disp-minimal">
          <button data-v="on" data-i18n="common.on" onclick="setMinimal('on')">on</button>
          <button data-v="off" data-i18n="common.off" onclick="setMinimal('off')">off</button>
        </span>
      </div>
      <div class="set-note" data-i18n="web.display.minimal_note">Hides the header (title + device info) and the footer. The now-playing card and the gear stay.</div>
    </section>

    <section>
      <h3 data-i18n="web.sound.title">Sound</h3>
      <div class="set-row">
        <span class="k" data-i18n="web.sound.dsee">DSEE</span>
        <span class="pill-toggle" id="snd-dsee">
          <button data-v="auto" data-i18n="common.auto" onclick="setSound('dsee','auto')">auto</button>
          <button data-v="off" data-i18n="common.off" onclick="setSound('dsee','off')">off</button>
        </span>
      </div>
      <div class="set-note" data-i18n="web.sound.dsee_note">Sony's upscaler. Auto tries to rebuild high frequencies lost in MP3/AAC. Off keeps the signal bit-perfect.</div>
      <div class="set-row">
        <span class="k" data-i18n="web.sound.dsd">DSD remastering</span>
        <span class="pill-toggle" id="snd-dsdRemastering">
          <button data-v="on" data-i18n="common.on" onclick="setSound('dsdRemastering','on')">on</button>
          <button data-v="off" data-i18n="common.off" onclick="setSound('dsdRemastering','off')">off</button>
        </span>
      </div>
      <div class="set-note" data-i18n="web.sound.dsd_note">Converts PCM (FLAC/WAV) to DSD before the DAC. Some hear it as smoother; off keeps the file's native format.</div>
      <div class="set-row">
        <span class="k" data-i18n="web.sound.gapless">Gapless</span>
        <span class="pill-toggle" id="snd-gaplessPlayback">
          <button data-v="auto" data-i18n="common.auto" onclick="setSound('gaplessPlayback','auto')">auto</button>
          <button data-v="off" data-i18n="common.off" onclick="setSound('gaplessPlayback','off')">off</button>
        </span>
      </div>
      <div class="set-note" data-i18n="web.sound.gapless_note">Removes the silence between consecutive tracks. Auto follows album metadata; off always inserts ~0.1 s.</div>
      <div class="set-row">
        <span class="k" data-i18n="web.sound.volnorm">Volume normalize</span>
        <span class="pill-toggle" id="snd-volumeNormalization">
          <button data-v="auto" data-i18n="common.auto" onclick="setSound('volumeNormalization','auto')">auto</button>
          <button data-v="off" data-i18n="common.off" onclick="setSound('volumeNormalization','off')">off</button>
        </span>
      </div>
      <div class="set-note" data-i18n="web.sound.volnorm_note">Evens out loudness between tracks using ReplayGain tags. Useful for shuffled playback across albums.</div>
      <div class="set-row">
        <span class="k" data-i18n="web.sound.oversampling">Oversampling</span>
        <span class="pill-toggle" id="snd-oversampling">
          <button data-v="precision" data-i18n="web.val.precision" onclick="setSound('oversampling','precision')">precision</button>
          <button data-v="normal" data-i18n="web.val.normal" onclick="setSound('oversampling','normal')">normal</button>
        </span>
      </div>
      <div class="set-note" data-i18n="web.sound.oversampling_note">DAC reconstruction filter shape. Precision = sharper cutoff (more accurate). Normal = softer (smoother to some).</div>
    </section>

    <section>
      <h3 data-i18n="web.playback.title">Playback</h3>
      <div class="set-row">
        <span class="k" data-i18n="web.playback.volume">Volume</span>
        <input type="range" id="vol-slider" min="0" max="100" value="50" oninput="onVolumeChange(this.value)" disabled>
      </div>
      <div class="set-note" id="vol-note" data-i18n="web.playback.volume_note">HAP-Z1ES has no internal amp — volume is fixed (controlled by your preamp / external amp).</div>
      <div class="set-row">
        <span class="k" data-i18n="web.playback.sleep">Sleep timer</span>
        <select id="sleep-sel" onchange="onSleepChange(this.value)">
          <option value="off" data-i18n="common.off">Off</option>
        </select>
      </div>
      <div class="set-note" data-i18n="web.playback.sleep_note">Turns the HAP off after the selected duration. Useful for falling asleep to music.</div>
    </section>

    <section>
      <h3 data-i18n="web.current.title">Current track</h3>
      <div class="set-row">
        <span class="k" data-i18n="web.current.favorite">Favorite</span>
        <div class="fav-row" id="fav-row">
          <button data-v="favorite" onclick="setFavorite('favorite')" data-i18n-title="web.fav.title.favorite" title="Mark as favorite">♥</button>
          <button data-v="normal" onclick="setFavorite('normal')" data-i18n-title="web.fav.title.clear" title="Clear favorite / dislike">—</button>
          <button data-v="dislike" onclick="setFavorite('dislike')" data-i18n-title="web.fav.title.dislike" title="Mark as dislike">👎</button>
        </div>
      </div>
      <div class="set-note" id="fav-note" data-i18n="web.current.favorite_note">Marks the current track in the HAP library. Buttons disable when playing a non-HDD source (Spotify, radio).</div>
    </section>
  </div>
</div>
<header>
  <h1>HAP-Revival</h1>
  <div class="device" id="device-info" data-i18n="web.connecting">connecting…</div>
</header>
<main>
  <div class="card" id="now-playing">
    <div class="cover placeholder" id="cover"></div>
    <div class="meta">
      <div class="state-tag" id="state">…</div>
      <div class="title" id="title">—</div>
      <div class="artist" id="artist"></div>
      <div class="album" id="album"></div>
      <div class="tech" id="tech"></div>
    </div>
    <div class="progress-wrap">
      <div class="progress-bar" id="progress-bar" data-i18n-title="web.seek_hint" title="Click to seek">
        <div class="progress-fill" id="progress-fill" style="width:0%"></div>
      </div>
      <div class="progress-times">
        <span id="t-position">0:00</span>
        <span id="t-duration">0:00</span>
      </div>
    </div>
    <div class="controls">
      <button class="btn" onclick="hapCall('previous')" data-i18n-title="web.ctrl.previous" title="Previous">⏮</button>
      <button class="btn primary" onclick="togglePlay()" id="btn-play" data-i18n-title="web.ctrl.play" title="Pause/resume">⏸</button>
      <button class="btn" onclick="hapCall('next')" data-i18n-title="web.ctrl.next" title="Next">⏭</button>
      <button class="btn danger" onclick="confirmStandby()" data-i18n-title="web.ctrl.standby" title="Standby">⏻</button>
    </div>
  </div>
  <div class="card library" id="library-card">
    <div class="lib-head">
      <span class="lib-title" data-i18n="web.lib.title">Library</span>
      <button class="lib-toggle" id="lib-toggle" onclick="toggleLibrary()" data-i18n="web.lib.open">Browse</button>
    </div>
    <div id="lib-body" hidden>
      <div class="lib-tabs">
        <button class="lib-tab" onclick="libRoot('artists')" data-i18n="web.lib.artists">Artists</button>
        <button class="lib-tab" onclick="libRoot('albums')" data-i18n="web.lib.albums">Albums</button>
        <button class="lib-tab" onclick="libRoot('playlists')" data-i18n="web.lib.playlists">Playlists</button>
        <button class="lib-tab" onclick="libRoot('favorites')" data-i18n="web.lib.favorites">Favorites</button>
      </div>
      <input class="lib-search" id="lib-search" type="search" autocomplete="off"
             oninput="libSearchInput()" data-i18n-placeholder="web.lib.search_ph" placeholder="Search…">
      <div class="lib-crumbs" id="lib-crumbs"></div>
      <div class="lib-list" id="lib-list"></div>
      <div class="lib-foot">
        <button class="lib-more" id="lib-more" hidden onclick="libMore()" data-i18n="web.lib.more">Load more</button>
        <span class="set-note" id="lib-note"></span>
      </div>
    </div>
  </div>
  <div class="card settings">
    <table>
      <tr><td class="k" data-i18n="web.tbl.dsee">DSEE</td><td class="v" id="s-dsee">—</td></tr>
      <tr><td class="k" data-i18n="web.tbl.dsd">DSD remastering</td><td class="v" id="s-dsd">—</td></tr>
      <tr><td class="k" data-i18n="web.tbl.gapless">Gapless playback</td><td class="v" id="s-gapless">—</td></tr>
      <tr><td class="k" data-i18n="web.tbl.volnorm">Volume normalization</td><td class="v" id="s-volnorm">—</td></tr>
      <tr><td class="k" data-i18n="web.tbl.oversampling">Oversampling</td><td class="v" id="s-oversample">—</td></tr>
    </table>
  </div>
  <div id="error-banner"></div>
</main>
<footer>
  <a href="https://github.com/Guillain-RDCDE/HAP-Revival" target="_blank">github.com/Guillain-RDCDE/HAP-Revival</a> · <span data-i18n="web.footer.live">live updates</span> · <span data-i18n="web.footer.stdlib">stdlib only</span> · MIT
</footer>
<script>
/* ===== i18n (embedded: every catalog, so switching is instant + offline) ===== */
const I18N = __I18N_JSON__;
const LANGS = __LANGS_JSON__;
const LANG_KEY = "hap-revival.lang";
let LANG = localStorage.getItem(LANG_KEY) || "__DEFAULT_LANG__";
if (!I18N[LANG]) LANG = "en";

function t(key, params) {
  let s = (I18N[LANG] && I18N[LANG][key]) || (I18N["en"] && I18N["en"][key]) || key;
  if (params) for (const k in params) s = s.split("{" + k + "}").join(params[k]);
  return s;
}
function applyI18n() {
  document.documentElement.setAttribute("lang", LANG);
  document.title = t("web.title");
  document.querySelectorAll("[data-i18n]").forEach(el => {
    el.textContent = t(el.getAttribute("data-i18n"));
  });
  document.querySelectorAll("[data-i18n-title]").forEach(el => {
    el.title = t(el.getAttribute("data-i18n-title"));
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    el.placeholder = t(el.getAttribute("data-i18n-placeholder"));
  });
  // The library toggle and its rows carry state, not a fixed label, so the
  // blanket pass above would reset them to "Browse" and to English counts.
  const toggle = document.getElementById("lib-toggle");
  if (toggle) toggle.textContent = libOpen ? t("web.lib.close") : t("web.lib.open");
  if (libOpen && libStack.length) { libCrumbs(); libRender(); }
}
function buildLangSelect() {
  const sel = document.getElementById("lang-sel");
  if (!sel) return;
  sel.innerHTML = "";
  LANGS.forEach(l => {
    const o = document.createElement("option");
    o.value = l.code;
    o.textContent = l.name;
    if (l.code === LANG) o.selected = true;
    sel.appendChild(o);
  });
}
function setLang(code) {
  if (!I18N[code]) return;
  LANG = code;
  localStorage.setItem(LANG_KEY, code);
  applyI18n();
}
function confirmStandby() {
  if (confirm(t("web.confirm_standby"))) hapCall("standby");
}
function powerLabel(p) {
  if (p === "active") return t("web.power.active");
  if (p === "standby" || p === "off") return t("web.power.standby");
  return p;
}

let lastState = null;
let lastDuration = 0;
let lastUri = "";   // the player's uri for the current track, e.g. audio:track?id=N
// Anchors for the local progress ticker: the last position the player told us,
// when it told us, and whether the clock should be running.
let localPosition = 0;
let localDuration = 0;
let localPlaying = false;
let localStamp = 0;

/* ===== Theme handling ===== */
const THEME_KEY = "hap-revival.theme";
const CUSTOM_COLOR_KEY = "hap-revival.customColor";
const MINIMAL_KEY = "hap-revival.minimalMode";
const VALID_THEMES = ["ambient", "cover-solid", "dark", "custom"];

/* Perceptual luminance (Rec. 601). 0=black, 1=white. Threshold ~0.6 works
   well for our 80px-blurred backgrounds (the blur itself averages colors
   so a single accent RGB approximates the visible brightness). */
function bgLuminance(r, g, b) {
  return (0.299 * r + 0.587 * g + 0.114 * b) / 255;
}
function hexToRgb(hex) {
  hex = hex.replace("#", "");
  if (hex.length === 3) hex = hex.split("").map(c => c + c).join("");
  return [parseInt(hex.slice(0,2),16), parseInt(hex.slice(2,4),16), parseInt(hex.slice(4,6),16)];
}
function applyContrast(rgb) {
  if (!rgb) return;
  const isLight = bgLuminance(rgb[0], rgb[1], rgb[2]) > 0.6;
  document.documentElement.classList.toggle("bg-is-light", isLight);
}
function currentBgRgb() {
  const theme = document.documentElement.getAttribute("data-theme") || "ambient";
  if (theme === "dark") return [14, 14, 16];
  if (theme === "custom") {
    const hex = localStorage.getItem(CUSTOM_COLOR_KEY) || "#1a1f2c";
    return hexToRgb(hex);
  }
  // ambient + cover-solid both use the cover-derived accent
  const accent = getComputedStyle(document.documentElement).getPropertyValue("--accent").trim();
  const m = accent.match(/rgb\\((\\d+),\\s*(\\d+),\\s*(\\d+)\\)/);
  return m ? [parseInt(m[1]), parseInt(m[2]), parseInt(m[3])] : null;
}

function setTheme(name) {
  if (!VALID_THEMES.includes(name)) name = "ambient";
  if (name === "ambient") {
    document.documentElement.removeAttribute("data-theme");
  } else {
    document.documentElement.setAttribute("data-theme", name);
  }
  localStorage.setItem(THEME_KEY, name);
  const radio = document.getElementById("t-" + name);
  if (radio) radio.checked = true;
  // Visual: highlight the active option's row + reset the others
  VALID_THEMES.forEach(t => {
    const el = document.getElementById("opt-" + t);
    if (el) el.classList.toggle("active", t === name);
  });
  // Adapt text color to the new background's luminance
  applyContrast(currentBgRgb());
  // Debug indicator in the panel + console log so it's easy to see what's firing
  const dbg = document.getElementById("theme-debug");
  if (dbg) dbg.textContent = "current: " + name + " · data-theme=" + (document.documentElement.getAttribute("data-theme") || "(none)");
  console.log("[HAP-Revival] setTheme:", name, "| <html data-theme> =", document.documentElement.getAttribute("data-theme"));
}

function setCustomColor(hex) {
  document.documentElement.style.setProperty("--custom-bg", hex);
  localStorage.setItem(CUSTOM_COLOR_KEY, hex);
  // Auto-switch to custom theme when user touches the picker.
  // setTheme() recomputes contrast, so picking a bright color also flips
  // text dark immediately.
  setTheme("custom");
}

function setMinimal(state) {
  const on = state === "on";
  document.documentElement.classList.toggle("minimal", on);
  localStorage.setItem(MINIMAL_KEY, on ? "on" : "off");
  // Reflect on the panel pills
  const wrap = document.getElementById("disp-minimal");
  if (wrap) {
    wrap.querySelectorAll("button").forEach(b => {
      b.classList.toggle("active", b.getAttribute("data-v") === (on ? "on" : "off"));
    });
  }
}

function toggleSettings() {
  document.getElementById("settings-panel").classList.toggle("open");
  document.getElementById("gear-btn").classList.toggle("open");
}

/* ===== Sound / Playback / Favorite controls ===== */

async function setSound(target, value) {
  await hapCall("set-sound", {target: target, value: value});
}

function onVolumeChange(v) {
  // Debounce: only fire on release? For now, fire on each change but throttle.
  clearTimeout(window._volTimer);
  window._volTimer = setTimeout(() => hapCall("set-volume", {volume: parseInt(v)}), 200);
}

async function onSleepChange(secStr) {
  if (secStr === "off") {
    await hapCall("set-sleep-timer", {status: "off", sleep_sec: 0});
  } else {
    await hapCall("set-sleep-timer", {status: "on", sleep_sec: parseInt(secStr)});
  }
}

async function setFavorite(value) {
  await hapCall("set-favorite", {value: value});
}

function applySoundUI(snd) {
  if (!snd) return;
  const targets = {
    "dsee": snd.dsee, "dsdRemastering": snd.dsd_remastering,
    "gaplessPlayback": snd.gapless_playback, "volumeNormalization": snd.volume_normalization,
    "oversampling": snd.oversampling
  };
  for (const t in targets) {
    const cur = targets[t];
    const wrap = document.getElementById("snd-" + t);
    if (!wrap) continue;
    wrap.querySelectorAll("button").forEach(b => {
      b.classList.toggle("active", b.getAttribute("data-v") === cur);
    });
  }
}

function applySleepUI(timer) {
  const sel = document.getElementById("sleep-sel");
  if (!sel || !timer) return;
  // Build option list once from candidate_sec
  if (sel.options.length <= 1 && timer.candidate_sec && timer.candidate_sec.length) {
    timer.candidate_sec.forEach(sec => {
      const opt = document.createElement("option");
      opt.value = String(sec);
      const min = Math.round(sec / 60);
      opt.textContent = t("web.minutes", {n: min});
      sel.appendChild(opt);
    });
  }
  // Reflect current value
  if (timer.status === "off") sel.value = "off";
  else if (timer.sleep_sec > 0) sel.value = String(timer.sleep_sec);
}

function applyVolumeUI(vol) {
  const slider = document.getElementById("vol-slider");
  const note = document.getElementById("vol-note");
  if (!slider || !vol) return;
  if (vol.maxVolume <= 0) {
    slider.disabled = true;
    note.textContent = t("web.vol.no_amp");
  } else {
    slider.disabled = false;
    slider.min = vol.minVolume || 0;
    slider.max = vol.maxVolume;
    slider.step = vol.step || 1;
    if (vol.volume >= 0) slider.value = vol.volume;
    note.textContent = t("web.vol.amp", {step: vol.step || 1});
  }
}

function applyFavoriteUI(np) {
  const row = document.getElementById("fav-row");
  const note = document.getElementById("fav-note");
  if (!row || !np) return;
  const isHddTrack = np.uri && np.uri.startsWith("audio:track?id=");
  row.querySelectorAll("button").forEach(b => {
    b.disabled = !isHddTrack;
    b.classList.toggle("active", isHddTrack && b.getAttribute("data-v") === (np.favorite_type || "normal"));
  });
  note.textContent = isHddTrack
    ? t("web.fav.hdd")
    : t("web.fav.nonhdd", {src: np.storage_uri || "external"});
}

document.addEventListener("click", (e) => {
  if (!e.target.closest(".gear-wrap")) {
    document.getElementById("settings-panel").classList.remove("open");
    document.getElementById("gear-btn").classList.remove("open");
  }
});

// Restore saved theme + custom color + minimal mode on page load
(function initTheme() {
  const saved = localStorage.getItem(THEME_KEY) || "ambient";
  const customColor = localStorage.getItem(CUSTOM_COLOR_KEY);
  if (customColor) {
    document.documentElement.style.setProperty("--custom-bg", customColor);
    const picker = document.getElementById("custom-color");
    if (picker) picker.value = customColor;
  }
  setTheme(saved);
  // Restore minimal mode preference
  const minimal = localStorage.getItem(MINIMAL_KEY) || "off";
  setMinimal(minimal);
})();

function fmt(secs) {
  if (!secs || secs < 0) return "0:00";
  const m = Math.floor(secs / 60), s = Math.floor(secs % 60);
  return m + ":" + String(s).padStart(2, "0");
}

async function refresh() {
  try {
    const r = await fetch("/api/state");
    if (!r.ok) throw new Error("HTTP " + r.status);
    const d = await r.json();
    if (d.error) throw new Error(d.error);
    apply(d);
    document.getElementById("error-banner").innerHTML = "";
  } catch (e) {
    document.getElementById("error-banner").innerHTML =
      '<div class="error">' + t("web.err.unreachable", {msg: e.message}) + "</div>";
  }
}

function apply(d) {
  const np = d.now_playing, sys = d.system, snd = d.sound;
  document.getElementById("device-info").textContent =
    sys.model + " · " + t("web.firmware") + " " + sys.version + " · " + powerLabel(sys.power);
  document.getElementById("state").textContent = t("web.state." + np.state);
  document.getElementById("state").className = "state-tag " + np.state;
  document.getElementById("title").textContent = np.title || "—";
  document.getElementById("artist").textContent = np.artist || "";
  document.getElementById("album").textContent = np.album || "";
  const tech = np.codec
    ? (np.sample_rate_hz
        ? np.codec.toUpperCase() + " · " + (np.sample_rate_hz/1000) + " kHz / " + np.bit_depth + "-bit"
        : np.codec.toUpperCase())
    : (np.storage_uri ? t("web.np.streaming", {src: np.storage_uri}) : "");
  document.getElementById("tech").textContent = tech;

  const cover = document.getElementById("cover");
  if (np.cover_art_url) {
    cover.style.backgroundImage = "url('" + np.cover_art_url + "')";
    cover.classList.remove("placeholder");
  } else {
    cover.style.backgroundImage = "";
    cover.classList.add("placeholder");
  }
  document.getElementById("progress-fill").style.width = (np.progress * 100) + "%";
  document.getElementById("t-position").textContent = fmt(np.position_sec);
  document.getElementById("t-duration").textContent = fmt(np.duration_sec);
  lastDuration = np.duration_sec;
  // Keep the library's "now playing" highlight in step with the real player.
  if (lastUri !== (np.uri || "")) {
    lastUri = np.uri || "";
    if (libOpen && libStack.length) libRender();
  }

  // Anchor for the local progress ticker (see "Live updates" below).
  localPosition = np.position_sec || 0;
  localDuration = np.duration_sec || 0;
  localPlaying = np.state === "PLAYING";
  localStamp = Date.now();

  if (snd) {
    document.getElementById("s-dsee").textContent = snd.dsee || "—";
    document.getElementById("s-dsd").textContent = snd.dsd_remastering || "—";
    document.getElementById("s-gapless").textContent = snd.gapless_playback || "—";
    document.getElementById("s-volnorm").textContent = snd.volume_normalization || "—";
    document.getElementById("s-oversample").textContent = snd.oversampling || "—";
  }

  const btn = document.getElementById("btn-play");
  btn.textContent = np.state === "PLAYING" ? "⏸" : "▶";
  lastState = np.state;

  if (np.background_color_rgba) {
    const c = np.background_color_rgba;
    document.documentElement.style.setProperty("--accent", `rgb(${c[0]},${c[1]},${c[2]})`);
    document.documentElement.style.setProperty("--accent-soft", `rgba(${c[0]},${c[1]},${c[2]},0.35)`);
    // Recompute text contrast: cover changed, so the dominant color did too
    applyContrast(currentBgRgb());
  }

  // Update gear-panel settings UI from the same state payload
  applySoundUI(d.sound);
  applySleepUI(d.sleep_timer);
  applyVolumeUI(d.volume);
  applyFavoriteUI(np);
  // Ambient cover background: hand the cover URL to the CSS variable used by body::before
  if (np.cover_art_url) {
    document.documentElement.style.setProperty("--cover-url", `url("${np.cover_art_url}")`);
  } else {
    document.documentElement.style.setProperty("--cover-url", "none");
  }
}

function togglePlay() {
  // The HAP's `pausePlayingContent` is a true toggle (pause<->play).
  // The state-based branching we used to do here was racy + unreliable
  // for Spotify Connect; the toggle endpoint is rock solid.
  hapCall("toggle-playback");
}

async function hapCall(action, params) {
  try {
    const r = await fetch("/api/" + action, {
      method: "POST",
      headers: {"Content-Type": "application/json"},
      body: JSON.stringify(params || {})
    });
    if (!r.ok) {
      const txt = await r.text();
      throw new Error("HTTP " + r.status + ": " + txt);
    }
    setTimeout(refresh, 300);
  } catch (e) {
    document.getElementById("error-banner").innerHTML =
      '<div class="error">' + t("web.err.action", {msg: e.message}) + "</div>";
  }
}

/* ===== Library browser =====
   Two speeds, and the UI has to respect the difference. A root listing
   (artists / albums) makes the player count its whole catalog and can take a
   minute; anything scoped by id comes back in well under a second. So the root
   fetch shows a note explaining the wait, and drill-down does not.

   `libStack` is the navigation trail: each entry knows how to re-fetch itself,
   which makes Back free and avoids caching anything in the browser. */
let libStack = [];
let libOpen = false;

function toggleLibrary() {
  libOpen = !libOpen;
  document.getElementById("lib-body").hidden = !libOpen;
  document.getElementById("lib-toggle").textContent =
    libOpen ? t("web.lib.close") : t("web.lib.open");
  if (libOpen && !libStack.length) libRoot("artists");
}

function libMsg(html) {
  document.getElementById("lib-list").innerHTML = '<div class="lib-msg">' + html + "</div>";
}

function libRoot(kind) {
  const box = document.getElementById("lib-search");
  if (box) box.value = "";        // a tab click leaves search mode
  libStack = [{kind: kind, url: "/api/library/" + kind, label: t("web.lib." + kind)}];
  document.querySelectorAll(".lib-tab").forEach((b) =>
    b.classList.toggle("on", b.getAttribute("onclick") === "libRoot('" + kind + "')"));
  libLoad(true);
}

function libPush(entry) {
  libStack.push(entry);
  libLoad(true);
}

function libBack() {
  if (libStack.length > 1) { libStack.pop(); libLoad(true); }
}

function libCrumbs() {
  const el = document.getElementById("lib-crumbs");
  if (libStack.length <= 1) { el.innerHTML = ""; return; }
  const trail = libStack.map((s) => s.label).join(" › ");
  el.innerHTML = '<button onclick="libBack()">← ' + t("web.lib.back") + "</button> · " + trail;
}

async function libLoad(reset) {
  const top = libStack[libStack.length - 1];
  if (reset) { top.offset = 0; top.items = []; }
  libCrumbs();
  // Only a root listing is slow enough to need explaining.
  const slow = libStack.length === 1 && top.kind !== "playlists" && top.kind !== "favorites";
  if (reset) libMsg(t("web.lib.loading") + (slow ? "<br><br>" + t("web.lib.slow_note") : ""));
  document.getElementById("lib-more").hidden = true;
  try {
    const sep = top.url.includes("?") ? "&" : "?";
    const r = await fetch(top.url + sep + "offset=" + (top.offset || 0) + "&limit=200");
    if (!r.ok) throw new Error("HTTP " + r.status);
    const d = await r.json();
    if (d.error) throw new Error(d.error);
    top.items = (top.items || []).concat(d.items);
    top.offset = (top.offset || 0) + d.items.length;
    top.total = d.total;
    top.hasMore = d.has_more;
    libRender();
  } catch (e) {
    libMsg(t("web.lib.error", {msg: e.message}));
  }
}

function libMore() { libLoad(false); }

/* ----- search -----
   The player has no search endpoint and one request costs 30-60 s, so the
   server matches a harvested copy of the catalog instead. Until that harvest
   exists the box explains what it costs and offers to build it — it is never
   started behind the user's back, because it monopolises the player for about
   an hour and a half. */
let libSearchTimer = null;

function libSearchInput() {
  clearTimeout(libSearchTimer);
  libSearchTimer = setTimeout(libSearch, 200);   // one request per pause, not per key
}

async function libSearch() {
  const term = document.getElementById("lib-search").value.trim();
  if (!term) { if (libStack.length) libRender(); return; }
  try {
    const r = await fetch("/api/library/search?q=" + encodeURIComponent(term));
    const d = await r.json();
    if (!d.ready) { libOfferHarvest(d); return; }
    const items = [].concat(d.results.artists, d.results.albums, d.results.tracks);
    // Show results through the same trail machinery, so Back returns to
    // wherever the user was browsing before they typed.
    libStack = libStack.slice(0, 1).concat([{
      url: "", label: '"' + term + '"', items: items,
      total: items.length, hasMore: false, isSearch: true,
    }]);
    libCrumbs();
    libRender();
  } catch (e) {
    libMsg(t("web.lib.error", {msg: e.message}));
  }
}

function libOfferHarvest(state) {
  if (state.harvesting) {
    libMsg(t("web.lib.indexing") + "<br><br>" + (state.progress || ""));
    setTimeout(libSearch, 3000);
    return;
  }
  libMsg(t("web.lib.no_index") + '<br><br><button class="lib-more" onclick="libStartHarvest()">'
         + t("web.lib.build_index") + "</button>");
}

async function libStartHarvest() {
  libMsg(t("web.lib.indexing"));
  try {
    await fetch("/api/library/harvest", {method: "POST",
      headers: {"Content-Type": "application/json"}, body: "{}"});
  } catch (e) { /* the poll below reports whatever actually happened */ }
  setTimeout(libSearch, 1500);
}

function libRender() {
  const top = libStack[libStack.length - 1];
  const list = document.getElementById("lib-list");
  if (!top || !top.items) return;            // a load is still in flight
  if (!top.items.length) { libMsg(t("web.lib.empty")); return; }

  list.innerHTML = "";
  for (const item of top.items) {
    const row = document.createElement("div");
    row.className = "lib-row";
    const name = document.createElement("span");
    name.className = "n";
    name.textContent = item.name || "—";
    const side = document.createElement("span");
    side.className = "s";
    row.appendChild(name);
    row.appendChild(side);

    if (item.trackid !== undefined) {
      const c = item.codec || {};
      side.textContent = c.codec_type
        ? c.codec_type + " " + (c.sample_rate / 1000) + "kHz/" + c.bit_width + "bit"
        : "";
      // The uri the player reports for the current track is audio:track?id=N,
      // and N is this same trackid — so highlighting needs no extra lookup.
      if (lastUri === "audio:track?id=" + item.trackid) row.classList.add("playing");
      row.onclick = () => { hapCall("play-track", {track_id: item.trackid}); };
    } else if (item.albumid !== undefined) {
      side.textContent = t("web.lib.tracks", {n: item.number_of_tracks});
      row.onclick = () => libPush({
        url: "/api/library/albums/" + item.albumid + "/tracks",
        label: item.name,
      });
    } else if (item.artistid !== undefined) {
      side.textContent = t("web.lib.tracks", {n: item.number_of_tracks});
      row.onclick = () => libPush({
        url: "/api/library/artists/" + item.artistid + "/albums",
        label: item.name,
      });
    } else if (item.playlistid !== undefined) {
      side.textContent = t("web.lib.tracks", {n: item.number_of_tracks});
      row.onclick = () => libPush({
        url: "/api/library/playlists/" + item.playlistid + "/tracks",
        label: item.name,
      });
    }
    list.appendChild(row);
  }

  document.getElementById("lib-more").hidden = !top.hasMore;
  document.getElementById("lib-note").textContent =
    top.items.length + " / " + (top.total || top.items.length) + " · " + t("web.lib.play_hint");
}

document.getElementById("progress-bar").addEventListener("click", (e) => {
  if (!lastDuration) return;
  const rect = e.currentTarget.getBoundingClientRect();
  const frac = (e.clientX - rect.left) / rect.width;
  const pos = Math.max(0, Math.min(lastDuration, frac * lastDuration));
  hapCall("seek", {position_sec: pos});
});

/* ===== Live updates =====
   The player pushes a UDP notification the moment anything changes; the server
   turns that into a long-poll on /api/events. We refresh as soon as one lands,
   so a track change shows up immediately instead of on the next tick.

   The timer is still there for two reasons: it moves the progress bar, and it
   is the whole story when push is unavailable (player asleep, mock device, or
   --no-push). So it runs fast when push is off and slows right down when push
   is carrying the news. */
const TICK_PUSH_MS = 10000;
const TICK_POLL_MS = 3000;
let pushActive = false;
let generation = 0;
let tickTimer = null;

function scheduleTick() {
  clearTimeout(tickTimer);
  tickTimer = setTimeout(async () => {
    await refresh();
    scheduleTick();
  }, pushActive ? TICK_PUSH_MS : TICK_POLL_MS);
}

async function eventLoop() {
  for (;;) {
    try {
      const r = await fetch("/api/events?since=" + generation);
      if (!r.ok) throw new Error("HTTP " + r.status);
      const d = await r.json();
      const was = pushActive;
      pushActive = !!d.push;
      if (was !== pushActive) scheduleTick();   // retune the safety net
      if (d.generation > generation) {
        generation = d.generation;
        refresh();
      }
      if (!pushActive) await new Promise((r2) => setTimeout(r2, 5000));
    } catch (e) {
      // Server gone or endpoint absent — fall back to the timer and retry.
      if (pushActive) { pushActive = false; scheduleTick(); }
      await new Promise((r2) => setTimeout(r2, 5000));
    }
  }
}

/* Between refreshes the position is advanced locally, so the bar stays smooth
   at one frame a second no matter how rarely we talk to the player. */
setInterval(() => {
  if (!localPlaying || !localDuration) return;
  const pos = Math.min(localDuration, localPosition + (Date.now() - localStamp) / 1000);
  document.getElementById("progress-fill").style.width = (pos / localDuration * 100) + "%";
  document.getElementById("t-position").textContent = fmt(pos);
}, 1000);

buildLangSelect();
applyI18n();
refresh();
scheduleTick();
eventLoop();

/* ===== PWA: register the service worker (enables "installable" on
   Chrome/Edge/Android; harmless on iOS, which installs via the manifest +
   apple-touch-icon). The SW only caches the static icon set + an offline
   shell — never the live device state. */
if ("serviceWorker" in navigator) {
  window.addEventListener("load", () => {
    navigator.serviceWorker.register("/sw.js").catch(() => {});
  });
}
</script>
</body>
</html>
"""
# <<< HTML_PAGE TEMPLATE END <<<


# ===== PWA assets (served by the handler below) =====

PWA_DIR = Path(__file__).resolve().parent / "pwa"

# Web App Manifest — makes the page installable to the iOS/iPadOS/Android home
# screen as a standalone app. `display: standalone` drops the browser chrome.
MANIFEST = """{
  "name": "HAP-Revival",
  "short_name": "HAP",
  "description": "Control surface for the Sony HAP-Z1ES / HAP-S1",
  "start_url": "/",
  "scope": "/",
  "display": "standalone",
  "orientation": "portrait",
  "background_color": "#0e0e10",
  "theme_color": "#0e0e10",
  "icons": [
    {"src": "/pwa/icon-192.png", "sizes": "192x192", "type": "image/png"},
    {"src": "/pwa/icon-512.png", "sizes": "512x512", "type": "image/png"},
    {"src": "/pwa/icon-maskable-512.png", "sizes": "512x512", "type": "image/png", "purpose": "maskable"}
  ]
}
"""

# Service worker — caches only the static icon set + manifest (cache-first),
# and explicitly bypasses /api/* so live device state is never served stale.
SERVICE_WORKER = """const CACHE = "hap-revival-v1";
const ASSETS = [
  "/pwa/icon-192.png", "/pwa/icon-512.png",
  "/pwa/icon-maskable-512.png", "/pwa/apple-touch-icon.png",
  "/manifest.webmanifest"
];
self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});
self.addEventListener("fetch", (e) => {
  const url = new URL(e.request.url);
  if (url.pathname.startsWith("/api/")) return;  // never cache device state
  if (url.pathname.startsWith("/pwa/") || url.pathname === "/manifest.webmanifest") {
    e.respondWith(caches.match(e.request).then((r) => r || fetch(e.request)));
  }
});
"""


class PushWatcher:
    """Subscribes to the player's UDP push stream and counts what arrives.

    The browser long-polls `/api/events?since=N`; every notification bumps the
    generation, which releases every waiting request at once and makes the UI
    refresh the instant something actually changed, instead of on the next
    three-second tick.

    Degrades quietly. If the player refuses the subscription — powered off, or
    a mock device that doesn't implement it — `active` stays False and the UI
    falls back to its timer. The watcher keeps retrying in the background, so a
    player that comes online later starts pushing without a restart.
    """

    RETRY_SECONDS = 30

    def __init__(self, ip: str, listen_port: int = hap_notify.DEFAULT_LISTEN_PORT) -> None:
        self.ip = ip
        self.listen_port = listen_port
        self.generation = 0
        self.active = False
        self.last_error: str | None = None
        self._condition = threading.Condition()
        self._thread: threading.Thread | None = None

    def start(self) -> None:
        self._thread = threading.Thread(target=self._run, daemon=True)
        self._thread.start()

    def _bump(self) -> None:
        with self._condition:
            self.generation += 1
            self._condition.notify_all()

    def _run(self) -> None:
        while True:
            notifier = hap_notify.HapNotifier(self.ip, listen_port=self.listen_port)
            try:
                notifier.open()
                self.active = True
                self.last_error = None
                for _event in notifier.events():
                    self._bump()
            except (hap_notify.NotifyError, OSError) as exc:
                self.last_error = str(exc)
            finally:
                notifier.close()
                if self.active:
                    self.active = False
                    # Release the long-polls so the UI can fall back to its timer
                    # rather than hanging until their own deadline.
                    self._bump()
            time.sleep(self.RETRY_SECONDS)

    def wait_for_change(self, since: int, timeout: float) -> int:
        """Block until the generation moves past `since`, or `timeout` elapses.

        Returns the current generation either way — a caller that times out
        simply long-polls again.
        """
        deadline = time.monotonic() + timeout
        with self._condition:
            while self.generation <= since:
                remaining = deadline - time.monotonic()
                if remaining <= 0:
                    break
                self._condition.wait(remaining)
            return self.generation


class HarvestState:
    """The catalog behind search, and the background walk that builds it.

    Harvesting takes about ninety minutes and monopolises the player — the
    daemon handles one request at a time, so everything else stalls while it
    runs. It therefore never starts on its own: someone has to ask for it, and
    the UI says what it will cost before they do.
    """

    def __init__(self) -> None:
        self.data: dict | None = None
        self.running = False
        self.progress = ""
        self.error = ""
        self._lock = threading.Lock()

    def load_cached(self, host: str) -> None:
        """Pick up a harvest from an earlier run, if one is on disk."""
        self.data = hap_library.load_harvest(host)
        if self.data:
            counts = self.data.get("counts", {})
            self.progress = f"cached: {counts}"

    def start(self, library: hap_library.Library) -> bool:
        with self._lock:
            if self.running:
                return False
            self.running = True
        self.error = ""
        threading.Thread(target=self._run, args=(library,), daemon=True).start()
        return True

    def _run(self, library: hap_library.Library) -> None:
        def note(kind: str, seen: int, total: int) -> None:
            self.progress = f"{kind} {seen}/{total}"

        try:
            data = library.harvest(progress=note)
            hap_library.save_harvest(data)
            self.data = data
            self.progress = f"done: {data.get('counts', {})}"
        except hap_library.LibraryError as e:
            self.error = str(e)
            self.progress = "failed"
        finally:
            self.running = False


HARVEST = HarvestState()


class HAPHandler(BaseHTTPRequestHandler):
    """Serves /, /api/state (GET), /api/events (GET, long-poll), and
    /api/<action> (POST)."""

    hap: HAP  # set on subclass before serve
    push: PushWatcher | None = None  # set on subclass before serve
    library: hap_library.Library | None = None  # set on subclass before serve

    # Silence the default request logging
    def log_message(self, fmt, *args):
        return

    def _send_json(self, status: int, payload: Any) -> None:
        body = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        self.send_response(status)
        self.send_header("Content-Type", "application/json; charset=utf-8")
        self.send_header("Content-Length", str(len(body)))
        self.send_header("Cache-Control", "no-store")
        self.end_headers()
        self.wfile.write(body)

    def _send_bytes(
        self, status: int, content_type: str, body: bytes, extra: dict[str, str] | None = None
    ) -> None:
        self.send_response(status)
        self.send_header("Content-Type", content_type)
        self.send_header("Content-Length", str(len(body)))
        for k, v in (extra or {}).items():
            self.send_header(k, v)
        self.end_headers()
        self.wfile.write(body)

    def _serve_search(self, query: str) -> None:
        """Search the harvested catalog.

        The device has no search endpoint, and one request costs 30-60 s, so
        searching it directly is not an option. Instead the whole catalog is
        harvested once (about 90 minutes) and matched here, in memory.
        """
        args = urllib.parse.parse_qs(query)
        term = (args.get("q", [""])[0] or "").strip()
        harvest = HARVEST.data
        if harvest is None:
            self._send_json(
                200,
                {
                    "ready": False,
                    "harvesting": HARVEST.running,
                    "progress": HARVEST.progress,
                    "results": {"artists": [], "albums": [], "tracks": []},
                },
            )
            return
        results = (
            self.library.search(harvest, term, limit=40)
            if (self.library and term)
            else {"artists": [], "albums": [], "tracks": []}
        )
        self._send_json(
            200,
            {
                "ready": True,
                "harvesting": HARVEST.running,
                "progress": HARVEST.progress,
                "counts": harvest.get("counts", {}),
                "results": results,
            },
        )

    def _serve_library(self, what: str, query: str) -> None:
        """Back the library browser: /api/library/<collection>[/<id>/<sub>].

        Root listings cost 40-90 s on the device and are cached by the Library
        object; drill-down by id is sub-second and goes straight through. The
        browser therefore only ever waits on the first artists/albums fetch.
        """
        if self.library is None:
            self._send_json(503, {"error": "library unavailable"})
            return
        args = urllib.parse.parse_qs(query)

        def num(key: str, default: int) -> int:
            try:
                return int(args.get(key, [str(default)])[0])
            except (TypeError, ValueError):
                return default

        offset, limit = num("offset", 0), min(num("limit", 200), hap_library.MAX_LIMIT)
        parts = [p for p in what.split("/") if p]
        lib = self.library

        try:
            if parts == ["artists"]:
                page = lib.artists(offset, limit)
            elif parts == ["albums"]:
                page = lib.albums(offset, limit)
            elif parts == ["genres"]:
                page = lib.genres(offset, limit)
            elif parts == ["tracks"]:
                page = lib.tracks(offset, limit)
            elif parts == ["playlists"]:
                page = lib.playlists()
            elif parts == ["favorites"]:
                page = lib.favorites(offset, limit)
            elif len(parts) == 3 and parts[0] == "artists" and parts[2] == "albums":
                page = lib.artist_albums(int(parts[1]), offset, limit)
            elif len(parts) == 3 and parts[0] == "albums" and parts[2] == "tracks":
                page = lib.album_tracks(int(parts[1]), offset, limit)
            elif len(parts) == 3 and parts[0] == "playlists" and parts[2] == "tracks":
                page = lib.playlist_tracks(int(parts[1]), offset, limit)
            else:
                self.send_error(404)
                return
        except (hap_library.LibraryError, ValueError) as e:
            self._send_json(502, {"error": str(e)})
            return

        self._send_json(
            200,
            {
                "items": page.items,
                "total": page.total,
                "offset": page.offset,
                "limit": page.limit,
                "has_more": bool(page.next_url),
            },
        )

    def do_GET(self) -> None:
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path

        # ---- PWA static assets ----
        if path == "/manifest.webmanifest":
            self._send_bytes(
                200, "application/manifest+json; charset=utf-8", MANIFEST.encode("utf-8")
            )
            return
        if path == "/sw.js":
            # Service-Worker-Allowed lets the SW control the whole origin even
            # though it's served from /sw.js.
            self._send_bytes(
                200,
                "text/javascript; charset=utf-8",
                SERVICE_WORKER.encode("utf-8"),
                {"Service-Worker-Allowed": "/", "Cache-Control": "no-cache"},
            )
            return
        if path.startswith("/pwa/"):
            # Serve the committed icon set. Resolve against PWA_DIR and confirm
            # the result stays inside it — blocks any ../ path traversal.
            name = path[len("/pwa/") :]
            target = (PWA_DIR / name).resolve()
            if target.parent == PWA_DIR and target.suffix == ".png" and target.is_file():
                self._send_bytes(
                    200,
                    "image/png",
                    target.read_bytes(),
                    {"Cache-Control": "public, max-age=86400"},
                )
            else:
                self.send_error(404)
            return

        if path in ("/", "/index.html"):
            try:
                np = self.hap.now_playing()
                bg = np.background_color_rgba or (60, 60, 80, 255)
                cover = np.cover_art_url or ""
            except HAPError:
                bg = (60, 60, 80, 255)
                cover = ""
            # Re-read the source on each request — lets us iterate on the
            # template without restarting the server process. The HTML_PAGE
            # constant defined at module top is just the fallback if we
            # can't find ourselves on disk for any reason.
            template = _live_html_template() or HTML_PAGE
            cover_css = f'url("{cover}")' if cover else "none"
            # Pick the initial language: ?lang= query → Accept-Language → OS.
            # The browser can still switch instantly afterwards (localStorage),
            # since every catalog is embedded below.
            qs = urllib.parse.parse_qs(parsed.query)
            lang = i18n.detect_lang(
                accept_language=self.headers.get("Accept-Language"),
                override=qs.get("lang", [None])[0],
            )
            i18n_json = json.dumps(i18n.all_catalogs(), ensure_ascii=False)
            langs_json = json.dumps(i18n.language_options(), ensure_ascii=False)
            html = (
                template.replace("__ACCENT_R__", str(bg[0]))
                .replace("__ACCENT_G__", str(bg[1]))
                .replace("__ACCENT_B__", str(bg[2]))
                .replace("__INITIAL_COVER_URL__", cover_css)
                .replace("__I18N_JSON__", i18n_json)
                .replace("__LANGS_JSON__", langs_json)
                .replace("__DEFAULT_LANG__", lang)
                .replace("__LANG__", lang)
            )
            body = html.encode("utf-8")
            self.send_response(200)
            self.send_header("Content-Type", "text/html; charset=utf-8")
            self.send_header("Content-Length", str(len(body)))
            self.send_header("Cache-Control", "no-store, no-cache, must-revalidate")
            self.send_header("Pragma", "no-cache")
            self.send_header("Expires", "0")
            self.end_headers()
            self.wfile.write(body)
            return

        if path == "/api/events":
            # Long-poll. Returns as soon as the player pushes a notification,
            # or after EVENT_POLL_TIMEOUT so the connection never goes stale.
            # `push: false` tells the browser to keep its own timer running.
            if self.push is None:
                self._send_json(200, {"push": False, "generation": 0})
                return
            try:
                since = int(urllib.parse.parse_qs(parsed.query).get("since", ["0"])[0])
            except (TypeError, ValueError):
                since = 0
            generation = self.push.wait_for_change(since, EVENT_POLL_TIMEOUT)
            self._send_json(
                200,
                {
                    "push": self.push.active,
                    "generation": generation,
                    "error": self.push.last_error,
                },
            )
            return

        if path == "/api/library/search":
            self._serve_search(parsed.query)
            return

        if path.startswith("/api/library/"):
            self._serve_library(path[len("/api/library/") :], parsed.query)
            return

        if path == "/api/state":
            # Each call is best-effort: if one sub-fetch fails we still return
            # the rest so the UI stays usable.
            payload: dict = {}
            try:
                np = self.hap.now_playing()
                payload["now_playing"] = {
                    "state": np.state,
                    "title": np.title,
                    "artist": np.artist,
                    "album": np.album,
                    "uri": np.uri,
                    "storage_uri": np.storage_uri,
                    "position_sec": np.position_sec,
                    "duration_sec": np.duration_sec,
                    "progress": np.progress,
                    "codec": np.codec,
                    "sample_rate_hz": np.sample_rate_hz,
                    "bit_depth": np.bit_depth,
                    "cover_art_url": np.cover_art_url,
                    "background_color_rgba": np.background_color_rgba,
                    "favorite_type": np.favorite_type,
                }
            except HAPError as e:
                payload["now_playing"] = {"state": "STOPPED", "error": str(e)}
            try:
                sys_info = self.hap.system_info()
                payload["system"] = {
                    "model": sys_info.model,
                    "version": sys_info.version,
                    "power": self.hap.power_status(),
                }
            except HAPError as e:
                payload["system"] = {"error": str(e)}
            try:
                snd = self.hap.sound_settings()
                payload["sound"] = {
                    "dsee": snd.dsee,
                    "dsd_remastering": snd.dsd_remastering,
                    "gapless_playback": snd.gapless_playback,
                    "volume_normalization": snd.volume_normalization,
                    "oversampling": snd.oversampling,
                }
            except HAPError as e:
                payload["sound"] = {"error": str(e)}
            try:
                t = self.hap.sleep_timer()
                payload["sleep_timer"] = {
                    "status": t.status,
                    "remain_sec": t.remain_sec,
                    "sleep_sec": t.sleep_sec,
                    "candidate_sec": t.candidate_sec,
                }
            except HAPError as e:
                payload["sleep_timer"] = {"error": str(e)}
            try:
                vol = self.hap.volume_information()
                payload["volume"] = {
                    "volume": vol.get("volume", -1),
                    "minVolume": vol.get("minVolume", -1),
                    "maxVolume": vol.get("maxVolume", -1),
                    "step": vol.get("step", 1),
                    "mute": vol.get("mute", "off"),
                }
            except HAPError as e:
                payload["volume"] = {"error": str(e)}
            self._send_json(200, payload)
            return

        self.send_error(404)

    def do_POST(self) -> None:
        parsed = urllib.parse.urlparse(self.path)
        path = parsed.path
        length = int(self.headers.get("Content-Length", "0"))
        raw = self.rfile.read(length) if length > 0 else b""
        try:
            params = json.loads(raw) if raw else {}
        except json.JSONDecodeError:
            self._send_json(400, {"error": "invalid JSON body"})
            return

        try:
            if path == "/api/toggle-playback":
                # The reliable play/pause control. Sony's pausePlayingContent
                # is a toggle, so we just fire it and let the device flip.
                self.hap.toggle_playback()
            elif path == "/api/pause":
                self.hap.pause()
            elif path == "/api/resume":
                self.hap.resume()
            elif path == "/api/next":
                self.hap.next_track()
            elif path == "/api/previous":
                self.hap.previous_track()
            elif path == "/api/standby":
                self.hap.standby()
            elif path == "/api/wake":
                self.hap.wake()
            elif path == "/api/seek":
                self.hap.seek_seconds(float(params.get("position_sec", 0)))
            elif path == "/api/play-track":
                self.hap.play_track(int(params["track_id"]))
            elif path == "/api/library/harvest":
                if self.library is None:
                    self._send_json(503, {"error": "library unavailable"})
                    return
                started = HARVEST.start(self.library)
                self._send_json(200, {"started": started, "running": HARVEST.running})
                return
            elif path == "/api/set-sound":
                target = str(params["target"])
                value = str(params["value"])
                self.hap.set_sound_setting(target, value)
            elif path == "/api/set-volume":
                self.hap.set_volume(int(params["volume"]))
            elif path == "/api/mute-toggle":
                self.hap.mute_toggle()
            elif path == "/api/set-sleep-timer":
                self.hap.set_sleep_timer(
                    status=str(params.get("status", "off")),
                    sleep_sec=int(params.get("sleep_sec", 0)),
                )
            elif path == "/api/set-favorite":
                # Need the current track URI. Re-fetch since the JS may not pass it.
                np = self.hap.now_playing()
                if not (np.uri and np.uri.startswith("audio:track?id=")):
                    self._send_json(400, {"error": "favorite only works on HDD tracks"})
                    return
                track_id = int(np.uri.split("=", 1)[1])
                self.hap.set_favorite(track_id, str(params.get("value", "favorite")))
            else:
                self.send_error(404)
                return
        except HAPError as e:
            self._send_json(500, {"error": str(e)})
            return
        except (KeyError, ValueError) as e:
            self._send_json(400, {"error": f"bad params: {e}"})
            return

        self._send_json(200, {"ok": True})


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("ip", nargs="?", help="HAP device IP address (omit when using --demo)")
    parser.add_argument("--port", type=int, default=8080, help="Local HTTP port (default 8080)")
    parser.add_argument("--bind", default="127.0.0.1", help="Bind address (default 127.0.0.1)")
    parser.add_argument(
        "--demo",
        action="store_true",
        help="Start an in-process mock HAP and drive the UI from it — no device needed.",
    )
    parser.add_argument(
        "--no-push",
        action="store_true",
        help="Don't subscribe to the player's UDP notifications; poll on a timer instead.",
    )
    parser.add_argument(
        "--notify-port",
        type=int,
        default=hap_notify.DEFAULT_LISTEN_PORT,
        help=f"Local UDP port to receive notifications on (default {hap_notify.DEFAULT_LISTEN_PORT}).",
    )
    args = parser.parse_args()

    if args.demo:
        import mock_hap

        mock_hap.serve_in_thread("127.0.0.1", 60200)
        args.ip = "127.0.0.1"
        print("Demo mode: in-process mock HAP-Z1ES on 127.0.0.1:60200 (no hardware needed).")
    if not args.ip:
        parser.error("an ip address is required (or pass --demo for the mock device)")

    HAPHandler.hap = HAP(args.ip)
    HAPHandler.library = hap_library.Library(args.ip)
    HARVEST.load_cached(args.ip)
    if HARVEST.data:
        print(f"Library search index loaded from cache: {HARVEST.data.get('counts', {})}")
    try:
        info = HAPHandler.hap.system_info()
        print(f"Connected: {info.model} firmware {info.version} ({args.ip})")
    except HAPError as e:
        print(f"WARNING: could not connect to HAP on first try: {e}", file=sys.stderr)
        print("The web UI will still start; refresh in a browser once the device is online.")

    if args.no_push:
        print("Push notifications disabled; the UI will poll every 3s.")
    else:
        HAPHandler.push = PushWatcher(args.ip, listen_port=args.notify_port)
        HAPHandler.push.start()

    server = ThreadingHTTPServer((args.bind, args.port), HAPHandler)
    print(f"HAP-Revival web UI: http://{args.bind}:{args.port}")
    print("Press Ctrl+C to stop.")
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        print("\nStopping.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
